include: package:pedantic/analysis_options.yaml
linter:
  rules:
    avoid_print: true
    avoid_field_initializers_in_const_classes: true
analyzer:
  errors:
    body_might_complete_normally_nullable: false