name: burgundy_budgeting_app
description: Vlorish budgeting app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.12

environment:
  sdk: '>=2.17.0-0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  equatable: ^2.0.3
  flutter_bloc: 7.0.0
  dio: 4.0.4
  shared_preferences: ^2.0.15
  permission_handler: ^9.2.0
  get_it: ^7.2.0
  logger: ^1.0.0
  google_fonts: ^3.0.1
  fluro: ^2.0.3
  image_picker: ^0.8.4+2
  amazon_cognito_identity_dart_2: ^2.1.1
  url_launcher: 6.0.3
  url_launcher_web: 2.0.0
  flutter_typeahead: 4.1.1
  hydrated_bloc: 7.0.0
  path_provider: ^2.0.1
  syncfusion_flutter_charts: 20.4.42
  hive: 2.0.4
  hive_flutter: 1.1.0
  syncfusion_flutter_datepicker: 20.4.44
  sentry: ^6.0.1
  sentry_flutter: ^6.0.1
  package_info_plus: ^1.3.0
  petitparser: 4.4.0
  pubnub: ^4.1.3
  collection: ^1.16.0
  otp_text_field: ^1.1.3
  dropdown_button2: ^2.0.0
dev_dependencies:
  test: any
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
  build_runner: ^2.1.11

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  generate: true

  #flutter_intl:
  #  enabled: true

  assets:
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/images/icons/
    - assets/audio/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
