name:  E2E Test
# on:
#   workflow_dispatch:
#     inputs:
#       testBranch:
#         description: "Which branch to checkout and run test"
#         required: false
#         default: master
#   schedule:
#     - cron: "0 0 * * 1-5"
on: [push]

jobs:
  run-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.0"
          channel: "stable"
          
      - name: Setup Enviroments
        run: flutter pub get
      - run: sudo apt-get install -y xvfb pcregrep
      - run: chmod 777 ./integration_test/{testout.sh,resultChecker.sh}
      
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
      
      - run: chrome --version
      
      - name: Start Chrome
        run: chromedriver --port=4444 &
      
      - name: Run Sign In Testsuite
        run: xvfb-run --auto-servernum flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/signin_test.dart -d chrome | ./integration_test/testout.sh
      
      - name: Run Password Recovery Testsuite
        run: xvfb-run --auto-servernum flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/passwordRecovery_test.dart -d chrome | ./integration_test/testout.sh
      
      # - name: Run Sign Up Testsuite
      #   run: xvfb-run --auto-servernum flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/signup_test.dart -d chrome |./integration_test/testout.sh
      
      # - name: Run Forgot Password Testsuite
      #   run: xvfb-run --auto-servernum flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/forgot_password_test.dart -d chrome |./integration_test/testout.sh
      
      # - name: Run Profile Testsuite
      #   run: xvfb-run --auto-servernum flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/profile_test.dart -d chrome |./integration_test/testout.sh
      
      # - name: Run Profile Detail Testsuite
      #   run: xvfb-run --auto-servernum flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/profile_detail_test.dart -d chrome |./integration_test/testout.sh
      
      # - name: Run Personal Budget 1 Testsuite
      #   run: xvfb-run --auto-servernum flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/personal_budget_test.dart -d chrome |./integration_test/testout.sh
      
      # - name: Run Personal Budget 2 Testsuite
      #   run: xvfb-run --auto-servernum flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/personal_budget_test_1.dart -d chrome |./integration_test/testout.sh
      
      # - name: Run Personal Budget 3 Testsuite
      #   run: xvfb-run --auto-servernum flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/personal_budget_planned_test_Bar_T260.dart -d chrome |./integration_test/testout.sh
      
      # - name: Run Personal Budget 4 Testsuite
      #   run: xvfb-run --auto-servernum flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/personal_budget_actual_test_Bar_T260.dart -d chrome |./integration_test/testout.sh
      
      # - name: Run Personal Budget 5 Testsuite
      #   run: xvfb-run --auto-servernum flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/personal_budget_difference_test_Bar_T260.dart -d chrome |./integration_test/testout.sh
      
      # - name: Run Planned Personal Budget Testsuite
      #   run: xvfb-run --auto-servernum flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/planned_personal_budget_test.dart -d chrome |./integration_test/testout.sh
      
      # - name: Run Personal Budget Monthly Testsuite
      #   run: xvfb-run --auto-servernum flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/personal_budget_monthly_test.dart -d chrome |./integration_test/testout.sh
       
      # - name: Run Business Budget Testsuite
      #   run: xvfb-run --auto-servernum flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/business_budget_test.dart -d chrome |./integration_test/testout.sh
      
      # - name: Run Goals Testsuite
      #   run: xvfb-run --auto-servernum flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/goals_test.dart -d chrome |./integration_test/testout.sh
      
      - name: Read file contents
        id: read_file
        uses: juliangruber/read-file-action@v1
        with:
         path: ./integration_test/failTest.txt
        
      - name: Check Test Fail
        run: ./integration_test/resultChecker.sh ./integration_test/failTest.txt
        
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: ${{ steps.read_file.outputs.content }}
          SLACK_TITLE: Result Test
          SLACK_USERNAME: rtCamp
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()

#       - name: Notify Slack 
#         uses: craftech-io/slack-action@v1
#         with:
#           slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
#           status: ${{ job.status }}
#         if: always()
        
      - uses: actions/upload-artifact@v3
        with:
          name: failTest
          path: ./integration_test/failTest.txt
        if: always()
