name:  E2E Test
# on:
#   workflow_dispatch:
#     inputs:
#       testBranch:
#         description: "Which branch to checkout and run test"
#         required: false
#         default: master
#   schedule:
#     - cron: "0 0 * * 1-5"

on: [push]

jobs:
  run-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.0"
          channel: "stable"
      - run: flutter pub get
      - uses: browser-actions/setup-chrome@v1
      - run: chrome --version
      - run: chromedriver --port=4444 &
      - run: sudo apt-get install -y xvfb grep
      - run: chmod 777 ./integration_test/testout.sh
      - run: xvfb-run --auto-servernum flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/signin_test.dart | ./integration_test/testout.sh

      # - uses: GabrielBB/xvfb-action@v1
      #   with:
      #     run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/signin_test.dart -d chrome >> log/output.txt
      #     working-directory: ./ #optional

#       - uses: GabrielBB/xvfb-action@v1
#         with:
#           run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/signin_test.dart -d chrome |./integration_test/testout.sh
          
#       - uses: GabrielBB/xvfb-action@v1
#         with:
#           run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/signup_test.dart -d chrome |./integration_test/testout.sh
      
#       - uses: GabrielBB/xvfb-action@v1
#         with:
#           run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/forgot_password_test.dart -d chrome |./integration_test/testout.sh
      
#       - uses: GabrielBB/xvfb-action@v1
#         with:
#           run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/profile_test.dart -d chrome |./integration_test/testout.sh

#       - uses: GabrielBB/xvfb-action@v1
#         with:
#           run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/personal_budget_test.dart -d chrome |./integration_test/testout.sh

#       - uses: GabrielBB/xvfb-action@v1
#         with:
#           run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/business_budget_test.dart -d chrome |./integration_test/testout.sh

#       - name: Notify Slack 
#         uses: craftech-io/slack-action@v1
#         with:
#           slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
#           status: ${{ job.status }}
#         if: always()
      
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: output-log
      #     path: log
      #   if: always()
