name:  E2E Test
on:
  workflow_dispatch:
    inputs:
      testBranch:
        description: "Which branch to checkout and run test"
        required: false
        default: master
  # schedule:
  #   - cron: "0 0 * * 1-5"

jobs:
  run-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.0"
          channel: "stable"
        
      - uses: nanasess/setup-chromedriver@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
  
      - run: flutter doctor
      - run: flutter pub get
      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/signin_test.dart -d chrome