name:  E2E Test
on:
  workflow_dispatch:
    inputs:
      testBranch:
        description: "Which branch to checkout and run test"
        required: false
        default: master
  schedule:
    - cron: "0 0 * * 1-5"

jobs:
  run-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.0"
          channel: "stable"
      - run: flutter pub get
      - run: chromedriver --port=4444 &

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/signin_bar_t52_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/signin_bar_t54_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/signin_bar_t57_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/signin_bar_t58_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/signin_bar_t59_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/signin_bar_t60_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/signin_bar_t64_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/signin_bar_t65_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/signin_bar_t67_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/signin_bar_t68_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/signin_bar_t69_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/signin_bar_t80_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/signup_bar_t1_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/signup_bar_t2_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/signup_bar_t4_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/signup_bar_t5_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/signup_bar_t6_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/signup_bar_t7_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/signup_bar_t8_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/signup_bar_t9_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/signup_bar_t10_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/signup_bar_t11_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/signup_bar_t16_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/signup_bar_t17_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/signup_bar_t21_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/signup_bar_t62_test.dart -d web-server --browser-name chrome
        if: always()                        

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/profile_bar_t98_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/profile_bar_t99_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/profile_bar_t103_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/profile_bar_t104_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/profile_bar_t105_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/profile_bar_t106_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/profile_bar_t107_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/profile_bar_t108_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/profile_bar_t109_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/profile_bar_t110_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/profile_bar_t111_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/profile_bar_t112_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/profile_bar_t113_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/profile_bar_t117_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/profile_bar_t118_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/personal_budget_bar_t121_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/personal_budget_bar_t122_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/personal_budget_bar_t123_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/personal_budget_bar_t124_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/personal_budget_bar_t125_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/personal_budget_bar_t126_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/personal_budget_bar_t127_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/personal_budget_bar_t128_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/personal_budget_bar_t129_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/personal_budget_bar_t132_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/personal_budget_bar_t133_test.dart -d web-server --browser-name chrome
        if: always()
      
      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/personal_budget_bar_t134_test.dart -d web-server --browser-name chrome
        if: always()
      
      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/personal_budget_bar_t138_test.dart -d web-server --browser-name chrome
        if: always()
      
      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/personal_budget_bar_t140_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/forgot_password_bar_t66_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/forgot_password_bar_t72_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/forgot_password_bar_t74_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/forgot_password_bar_t75_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/forgot_password_bar_t76_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/forgot_password_bar_t77_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/forgot_password_bar_t78_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/forgot_password_bar_t80_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/forgot_password_bar_t81_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/forgot_password_bar_t82_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/forgot_password_bar_t84_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/forgot_password_bar_t85_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/forgot_password_bar_t86_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/forgot_password_bar_t91_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/forgot_password_bar_t92_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/forgot_password_bar_t93_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/forgot_password_bar_t94_test.dart -d web-server --browser-name chrome
        if: always()

      - run: flutter drive --driver test_driver/integration_test_driver.dart --target integration_test/forgot_password_bar_t95_test.dart -d web-server --browser-name chrome
        if: always()


      - name: Notify Slack 
        uses: craftech-io/slack-action@v1
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: ${{ job.status }}
        if: always()
